package core_test

// PC-120's own acceptance criterion, verbatim: "Golden report fixture byte-compared
// in CI (same version + same snapshot → identical report); negative-controlled."
// golden/fixtures/aws.report.json is generated by cmd/gen-golden-fixtures (the same
// generator that produces aws.ir.json/aws.findings.json) — this test re-runs the
// identical BuildReport call and asserts byte-for-byte JSON equality, proving the
// report is fully deterministic (NFR-1) for the same inputs.

import (
	"encoding/json"
	"os"
	"testing"

	"preflight/core"
)

// goldenReportGraphSVG is the report diagram the golden fixtures use: a FIXED placeholder, the
// same string cmd/gen-golden-fixtures embeds. Live Graphviz output is not used here because its
// bytes depend on the installed Graphviz version and the machine's fonts, so a fixture that embedded
// it would only be true on the machine that generated it (PC-6: the first real CI run failed exactly
// that way, 4,000 bytes off with apt's Graphviz). The real diagram is checked in render/: its DOT
// input byte-for-byte on any machine, and its SVG for structure and same-environment determinism
// everywhere, plus byte-for-byte where the checked-in fixture applies.
const goldenReportGraphPlaceholder = `<svg xmlns="http://www.w3.org/2000/svg"><title>golden report diagram placeholder: the real diagram is checked in render/ (structure and determinism in any environment, bytes where the fixture applies)</title></svg>`

func goldenReportGraphSVG(t *testing.T, _ *core.IR) string {
	t.Helper()
	return goldenReportGraphPlaceholder
}

func TestGoldenReport_ByteIdentical(t *testing.T) {
	ir := realGoldenIR(t)
	workload := loadGoldenWorkload(t)
	findings := core.BuildFindings(ir, workload)
	scorecard := core.BuildScorecard(findings, 1)
	report := core.BuildReport("golden", 1, goldenReportGraphSVG(t, ir), ir, workload, findings, scorecard, nil, core.PriceTable{}, nil)

	got, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	want, err := os.ReadFile("../golden/fixtures/aws.report.json")
	if err != nil {
		t.Fatalf("read golden fixture: %v (run `go run ./cmd/gen-golden-fixtures` if this report shape genuinely changed)", err)
	}

	if string(got) != string(want) {
		t.Fatalf("golden/fixtures/aws.report.json is stale — regenerate with `go run ./cmd/gen-golden-fixtures` and hand-verify the diff before committing.\ngot %d bytes, want %d bytes", len(got), len(want))
	}
}

// TestGoldenReport_ByteIdentical_NegativeControl proves the test above actually
// discriminates — a report built from a DELIBERATELY different session ID must NOT
// match the committed fixture. Without this, a bug that made TestGoldenReport_
// ByteIdentical compare two empty strings (or otherwise vacuously pass) would go
// unnoticed.
func TestGoldenReport_ByteIdentical_NegativeControl(t *testing.T) {
	ir := realGoldenIR(t)
	workload := loadGoldenWorkload(t)
	findings := core.BuildFindings(ir, workload)
	scorecard := core.BuildScorecard(findings, 1)
	report := core.BuildReport("deliberately-different-session-id", 1, goldenReportGraphSVG(t, ir), ir, workload, findings, scorecard, nil, core.PriceTable{}, nil)

	got, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	want, err := os.ReadFile("../golden/fixtures/aws.report.json")
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}

	if string(got) == string(want) {
		t.Fatal("a report built with a different session_id byte-matched the golden fixture — the byte-comparison test above cannot be trusting a real diff")
	}
}
