package core_test

// PC-120's own acceptance criterion, verbatim: "Golden report fixture byte-compared
// in CI (same version + same snapshot → identical report); negative-controlled."
// golden/fixtures/aws.report.json is generated by cmd/gen-golden-fixtures (the same
// generator that produces aws.ir.json/aws.findings.json) — this test re-runs the
// identical BuildReport call and asserts byte-for-byte JSON equality, proving the
// report is fully deterministic (NFR-1) for the same inputs.

import (
	"encoding/json"
	"os"
	"testing"

	"preflight/core"
)

func TestGoldenReport_ByteIdentical(t *testing.T) {
	ir := realGoldenIR(t)
	workload := loadGoldenWorkload(t)
	findings := core.BuildFindings(ir, workload)
	scorecard := core.BuildScorecard(findings, 1)
	report := core.BuildReport("golden", 1, ir, workload, findings, scorecard, nil, core.PriceTable{}, nil)

	got, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	want, err := os.ReadFile("../golden/fixtures/aws.report.json")
	if err != nil {
		t.Fatalf("read golden fixture: %v (run `go run ./cmd/gen-golden-fixtures` if this report shape genuinely changed)", err)
	}

	if string(got) != string(want) {
		t.Fatalf("golden/fixtures/aws.report.json is stale — regenerate with `go run ./cmd/gen-golden-fixtures` and hand-verify the diff before committing.\ngot %d bytes, want %d bytes", len(got), len(want))
	}
}

// TestGoldenReport_ByteIdentical_NegativeControl proves the test above actually
// discriminates — a report built from a DELIBERATELY different session ID must NOT
// match the committed fixture. Without this, a bug that made TestGoldenReport_
// ByteIdentical compare two empty strings (or otherwise vacuously pass) would go
// unnoticed.
func TestGoldenReport_ByteIdentical_NegativeControl(t *testing.T) {
	ir := realGoldenIR(t)
	workload := loadGoldenWorkload(t)
	findings := core.BuildFindings(ir, workload)
	scorecard := core.BuildScorecard(findings, 1)
	report := core.BuildReport("deliberately-different-session-id", 1, ir, workload, findings, scorecard, nil, core.PriceTable{}, nil)

	got, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	got = append(got, '\n')

	want, err := os.ReadFile("../golden/fixtures/aws.report.json")
	if err != nil {
		t.Fatalf("read golden fixture: %v", err)
	}

	if string(got) == string(want) {
		t.Fatal("a report built with a different session_id byte-matched the golden fixture — the byte-comparison test above cannot be trusting a real diff")
	}
}
