// Command gen-conformance-report is PC-119's third acceptance criterion: "coverage
// report lists every conformance test by area and ID." Rather than an in-memory
// registry every conformance test would need to call into (which cannot aggregate
// across areas anyway — each tests/aws-conformance/<area> package is its own separate
// `go test` binary/process, sharing no memory with any other), this statically parses
// every harness.Spec{...} composite literal under tests/aws-conformance/ via go/ast
// (cmd/conformancescan, shared with cmd/check-conformance-links) — the same "derive an
// artifact from source, don't hand-maintain it" discipline cmd/gen-golden-fixtures and
// cmd/gen-contracts already established for this project's other generated artifacts.
//
// Run with: go run ./cmd/gen-conformance-report
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"preflight/cmd/conformancescan"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}
	confDir := filepath.Join(root, "tests", "aws-conformance")

	entries, err := conformancescan.Scan(confDir)
	if err != nil {
		fail(err)
	}

	sort.Slice(entries, func(i, j int) bool {
		if entries[i].Area != entries[j].Area {
			return entries[i].Area < entries[j].Area
		}
		return entries[i].ID < entries[j].ID
	})

	report := renderReport(entries)
	outPath := filepath.Join(confDir, "COVERAGE.md")
	if err := os.WriteFile(outPath, []byte(report), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("wrote %s (%d conformance tests across %d areas)\n", outPath, len(entries), countAreas(entries))
}

func countAreas(entries []conformancescan.Entry) int {
	seen := map[string]bool{}
	for _, e := range entries {
		seen[e.Area] = true
	}
	return len(seen)
}

func renderReport(entries []conformancescan.Entry) string {
	var b strings.Builder
	b.WriteString("# AWS conformance test coverage\n\n")
	b.WriteString("Generated by `go run ./cmd/gen-conformance-report` — do not hand-edit; regenerate instead.\n\n")
	if len(entries) == 0 {
		b.WriteString("No conformance tests found.\n")
		return b.String()
	}

	currentArea := ""
	for _, e := range entries {
		if e.Area != currentArea {
			if currentArea != "" {
				b.WriteString("\n")
			}
			currentArea = e.Area
			fmt.Fprintf(&b, "## %s\n\n", currentArea)
		}
		fmt.Fprintf(&b, "- **%s** (`%s`): %s\n  Source: %s\n", e.ID, e.File, e.Rule, e.Source)
	}
	return b.String()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-conformance-report:", err)
	os.Exit(1)
}
