// Official AWS Architecture Icons, package 07312026, copied without modification.
// Names are matched to the AWS product directory. Aliases cover renamed services
// and resources belonging to the same service. Category icons are separate so a
// missing dedicated icon never borrows the mark of a different AWS service.
import type { NodeType } from "./goldenVocabulary";

export const AWS_SERVICE_ICON_FILES: Readonly<Record<string, string>> = {
  "aws_acm_certificate": "Arch_AWS-Certificate-Manager_48.svg",
  "aws_acmpca_certificate_authority": "Arch_AWS-Private-Certificate-Authority_48.svg",
  "aws_amplify_app": "Arch_AWS-Amplify_48.svg",
  "aws_api_gateway_rest_api": "Arch_Amazon-API-Gateway_48.svg",
  "aws_appmesh_mesh": "Arch_AWS-App-Mesh_48.svg",
  "aws_apprunner_service": "Arch_AWS-App-Runner_48.svg",
  "aws_autoscaling_group": "Arch_Amazon-EC2-Auto-Scaling_48.svg",
  "aws_batch_job_definition": "Arch_AWS-Batch_48.svg",
  "aws_cloud_directory_directory": "Arch_Amazon-Cloud-Directory_48.svg",
  "aws_cloudfront_distribution": "Arch_Amazon-CloudFront_48.svg",
  "aws_cloudhsm_v2_cluster": "Arch_AWS-CloudHSM_48.svg",
  "aws_cloudsearch_domain": "Arch_Amazon-CloudSearch_48.svg",
  "aws_cloudwatch_event_bus": "Arch_Amazon-EventBridge_48.svg",
  "aws_cognito_user_pool": "Arch_Amazon-Cognito_48.svg",
  "aws_db_instance": "Arch_Amazon-RDS_48.svg",
  "aws_db_subnet_group": "Arch_Amazon-RDS_48.svg",
  "aws_deadline_farm": "Arch_AWS-Deadline-Cloud_48.svg",
  "aws_directory_service_directory": "Arch_AWS-Directory-Service_48.svg",
  "aws_docdb_cluster": "Arch_Amazon-DocumentDB_48.svg",
  "aws_dx_connection": "Arch_AWS-Direct-Connect_48.svg",
  "aws_dynamodb_global_table": "Arch_Amazon-DynamoDB_48.svg",
  "aws_dynamodb_table": "Arch_Amazon-DynamoDB_48.svg",
  "aws_ec2_transit_gateway": "Arch_AWS-Transit-Gateway_48.svg",
  "aws_ecr_repository": "Arch_Amazon-Elastic-Container-Registry_48.svg",
  "aws_ecs_service": "Arch_Amazon-Elastic-Container-Service_48.svg",
  "aws_ecs_task_definition": "Res_Amazon-Elastic-Container-Service_Task_48.svg",
  "aws_eks_cluster": "Arch_Amazon-Elastic-Kubernetes-Service_48.svg",
  "aws_eks_node_group": "Arch_Amazon-Elastic-Kubernetes-Service_48.svg",
  "aws_elastic_beanstalk_environment": "Arch_AWS-Elastic-Beanstalk_48.svg",
  "aws_elasticache_replication_group": "Arch_Amazon-ElastiCache_48.svg",
  "aws_elasticache_serverless_cache": "Arch_Amazon-ElastiCache_48.svg",
  "aws_elasticache_subnet_group": "Arch_Amazon-ElastiCache_48.svg",
  "aws_emr_cluster": "Arch_Amazon-EMR_48.svg",
  "aws_fms_policy": "Arch_AWS-Firewall-Manager_48.svg",
  "aws_gamelift_fleet": "Arch_Amazon-GameLift-Servers_48.svg",
  "aws_glacier_vault": "Arch_Amazon-Simple-Storage-Service-Glacier_48.svg",
  "aws_globalaccelerator_accelerator": "Arch_AWS-Global-Accelerator_48.svg",
  "aws_glue_job": "Arch_AWS-Glue_48.svg",
  "aws_iam_role": "Arch_AWS-Identity-and-Access-Management_48.svg",
  "aws_instance": "Arch_Amazon-EC2_48.svg",
  "aws_internet_gateway": "Res_Amazon-VPC_Internet-Gateway_48.svg",
  "aws_keyspaces_table": "Arch_Amazon-Keyspaces_48.svg",
  "aws_kinesis_firehose_delivery_stream": "Arch_Amazon-Data-Firehose_48.svg",
  "aws_kinesis_stream": "Arch_Amazon-Kinesis_48.svg",
  "aws_kinesisanalyticsv2_application": "Arch_Amazon-Managed-Service-for-Apache-Flink_48.svg",
  "aws_kms_key": "Arch_AWS-Key-Management-Service_48.svg",
  "aws_lambda_function": "Arch_AWS-Lambda_48.svg",
  "aws_lb": "Arch_Elastic-Load-Balancing_48.svg",
  "aws_lightsail_instance": "Arch_Amazon-Lightsail_48.svg",
  "aws_memorydb_cluster": "Arch_Amazon-MemoryDB_48.svg",
  "aws_mq_broker": "Arch_Amazon-MQ_48.svg",
  "aws_msk_cluster": "Arch_Amazon-Managed-Streaming-for-Apache-Kafka_48.svg",
  "aws_mwaa_environment": "Arch_Amazon-Managed-Workflows-for-Apache-Airflow_48.svg",
  "aws_nat_gateway": "Res_Amazon-VPC_NAT-Gateway_48.svg",
  "aws_neptune_cluster": "Arch_Amazon-Neptune_48.svg",
  "aws_network_acl": "Res_Amazon-VPC_Network-Access-Control-List_48.svg",
  "aws_networkfirewall_firewall": "Arch_AWS-Network-Firewall_48.svg",
  "aws_networkmanager_core_network": "Arch_AWS-Cloud-WAN_48.svg",
  "aws_opensearch_domain": "Arch_Amazon-OpenSearch-Service_48.svg",
  "aws_pcs_cluster": "Arch_AWS-Parallel-Computing-Service_48.svg",
  "aws_ram_resource_share": "Arch_AWS-Resource-Access-Manager_48.svg",
  "aws_rds_cluster": "Arch_Amazon-Aurora_48.svg",
  "aws_redshift_cluster": "Arch_Amazon-Redshift_48.svg",
  "aws_route53_record": "Arch_Amazon-Route-53_48.svg",
  "aws_route53_resolver_endpoint": "Res_Amazon-Route-53_Resolver_48.svg",
  "aws_route53_zone": "Res_Amazon-Route-53-Hosted-Zone_48.svg",
  "aws_s3_bucket": "Arch_Amazon-Simple-Storage-Service_48.svg",
  "aws_secretsmanager_secret": "Arch_AWS-Secrets-Manager_48.svg",
  "aws_service:a2i": "Arch_Amazon-Augmented-AI-A2I_48.svg",
  "aws_service:app-studio": "Arch_AWS-App-Studio_48.svg",
  "aws_service:appconfig": "Arch_AWS-AppConfig_48.svg",
  "aws_service:appfabric": "Arch_AWS-AppFabric_48.svg",
  "aws_service:appflow": "Arch_Amazon-AppFlow_48.svg",
  "aws_service:application-discovery-service": "Arch_AWS-Application-Discovery-Service_48.svg",
  "aws_service:application-recovery-controller-arc": "Arch_Amazon-Application-Recovery-Controller_48.svg",
  "aws_service:appsync": "Arch_AWS-AppSync_48.svg",
  "aws_service:artifact": "Arch_AWS-Artifact_48.svg",
  "aws_service:athena": "Arch_Amazon-Athena_48.svg",
  "aws_service:audit-manager": "Arch_AWS-Audit-Manager_48.svg",
  "aws_service:b2b-data-interchange": "Arch_AWS-B2B-Data-Interchange_48.svg",
  "aws_service:backup": "Arch_AWS-Backup_48.svg",
  "aws_service:bedrock": "Arch_Amazon-Bedrock_48.svg",
  "aws_service:bedrock-agentcore": "Arch_Amazon-Bedrock-AgentCore_48.svg",
  "aws_service:braket": "Arch_Amazon-Braket_48.svg",
  "aws_service:chime": "Arch_Amazon-Chime_48.svg",
  "aws_service:chime-sdk": "Arch_Amazon-Chime-SDK_48.svg",
  "aws_service:clean-rooms": "Arch_AWS-Clean-Rooms_48.svg",
  "aws_service:cloud-control-api": "Arch_AWS-Cloud-Control-API_48.svg",
  "aws_service:cloud-development-kit-aws-cdk": "Arch_AWS-Cloud-Development-Kit_48.svg",
  "aws_service:cloud9": "Arch_AWS-Cloud9_48.svg",
  "aws_service:cloudformation": "Arch_AWS-CloudFormation_48.svg",
  "aws_service:cloudshell": "Arch_AWS-CloudShell_48.svg",
  "aws_service:cloudtrail": "Arch_AWS-CloudTrail_48.svg",
  "aws_service:cloudwatch": "Arch_Amazon-CloudWatch_48.svg",
  "aws_service:codeartifact": "Arch_AWS-CodeArtifact_48.svg",
  "aws_service:codebuild": "Arch_AWS-CodeBuild_48.svg",
  "aws_service:codecatalyst": "Arch_Amazon-CodeCatalyst_48.svg",
  "aws_service:codedeploy": "Arch_AWS-CodeDeploy_48.svg",
  "aws_service:codeguru": "Arch_Amazon-CodeGuru_48.svg",
  "aws_service:codepipeline": "Arch_AWS-CodePipeline_48.svg",
  "aws_service:comprehend": "Arch_Amazon-Comprehend_48.svg",
  "aws_service:comprehend-medical": "Arch_Amazon-Comprehend-Medical_48.svg",
  "aws_service:compute-optimizer": "Arch_AWS-Compute-Optimizer_48.svg",
  "aws_service:config": "Arch_AWS-Config_48.svg",
  "aws_service:connect-customer": "Arch_Amazon-Connect_48.svg",
  "aws_service:control-tower": "Arch_AWS-Control-Tower_48.svg",
  "aws_service:data-exchange": "Arch_AWS-Data-Exchange_48.svg",
  "aws_service:data-transfer-terminal": "Arch_AWS-Data-Transfer-Terminal_48.svg",
  "aws_service:database-migration-service": "Arch_AWS-Database-Migration-Service_48.svg",
  "aws_service:datasync": "Arch_AWS-DataSync_48.svg",
  "aws_service:datazone": "Arch_Amazon-DataZone_48.svg",
  "aws_service:dcv": "Arch_Amazon-DCV_48.svg",
  "aws_service:deep-learning-amis": "Arch_AWS-Deep-Learning-AMIs_48.svg",
  "aws_service:deep-learning-containers": "Arch_AWS-Deep-Learning-Containers_48.svg",
  "aws_service:detective": "Arch_Amazon-Detective_48.svg",
  "aws_service:device-farm": "Arch_AWS-Device-Farm_48.svg",
  "aws_service:devops-agent": "Arch_AWS-DevOps-Agent_48.svg",
  "aws_service:devops-guru": "Arch_Amazon-DevOps-Guru_48.svg",
  "aws_service:ec2-image-builder": "Arch_Amazon-EC2-Image-Builder_48.svg",
  "aws_service:elastic-block-store": "Arch_Amazon-Elastic-Block-Store_48.svg",
  "aws_service:elastic-disaster-recovery": "Arch_AWS-Elastic-Disaster-Recovery_48.svg",
  "aws_service:elastic-file-system": "Arch_Amazon-EFS_48.svg",
  "aws_service:elastic-vmware-service": "Arch_Amazon-Elastic-VMware-Service_48.svg",
  "aws_service:elemental-inference": "Arch_AWS-Elemental-Inference_48.svg",
  "aws_service:elemental-mediaconnect": "Arch_AWS-Elemental-MediaConnect_48.svg",
  "aws_service:elemental-mediaconvert": "Arch_AWS-Elemental-MediaConvert_48.svg",
  "aws_service:elemental-medialive": "Arch_AWS-Elemental-MediaLive_48.svg",
  "aws_service:elemental-mediapackage": "Arch_AWS-Elemental-MediaPackage_48.svg",
  "aws_service:elemental-mediatailor": "Arch_AWS-Elemental-MediaTailor_48.svg",
  "aws_service:elemental-on-premises": "Arch_AWS-Elemental-Appliances-&-Software_48.svg",
  "aws_service:end-user-messaging-push": "Arch_AWS-End-User-Messaging_48.svg",
  "aws_service:end-user-messaging-sms": "Arch_AWS-End-User-Messaging_48.svg",
  "aws_service:end-user-messaging-social": "Arch_AWS-End-User-Messaging_48.svg",
  "aws_service:entity-resolution": "Arch_AWS-Entity-Resolution_48.svg",
  "aws_service:fargate": "Arch_AWS-Fargate_48.svg",
  "aws_service:fault-injection-service": "Arch_AWS-Fault-Injection-Service_48.svg",
  "aws_service:finspace": "Arch_Amazon-FinSpace_48.svg",
  "aws_service:forecast": "Arch_Amazon-Forecast_48.svg",
  "aws_service:fraud-detector": "Arch_Amazon-Fraud-Detector_48.svg",
  "aws_service:freertos": "Arch_FreeRTOS_48.svg",
  "aws_service:fsx": "Arch_Amazon-FSx_48.svg",
  "aws_service:gamelift-streams": "Arch_Amazon-GameLift-Streams_48.svg",
  "aws_service:ground-station": "Arch_AWS-Ground-Station_48.svg",
  "aws_service:guardduty": "Arch_Amazon-GuardDuty_48.svg",
  "aws_service:health": "Arch_AWS-Health-Dashboard_48.svg",
  "aws_service:healthimaging": "Arch_AWS-HealthImaging_48.svg",
  "aws_service:healthlake": "Arch_AWS-HealthLake_48.svg",
  "aws_service:healthomics": "Arch_AWS-HealthOmics_48.svg",
  "aws_service:infrastructure-composer": "Arch_AWS-Infrastructure-Composer_48.svg",
  "aws_service:inspector": "Arch_Amazon-Inspector_48.svg",
  "aws_service:interactive-video-service": "Arch_Amazon-Interactive-Video-Service_48.svg",
  "aws_service:interconnect": "Arch_AWS-Interconnect_48.svg",
  "aws_service:iot-core": "Arch_AWS-IoT-Core_48.svg",
  "aws_service:iot-device-defender": "Arch_AWS-IoT-Device-Defender_48.svg",
  "aws_service:iot-device-management": "Arch_AWS-IoT-Device-Management_48.svg",
  "aws_service:iot-expresslink": "Arch_AWS-IoT-ExpressLink_48.svg",
  "aws_service:iot-fleetwise": "Arch_AWS-IoT-FleetWise_48.svg",
  "aws_service:iot-greengrass": "Arch_AWS-IoT-Greengrass_48.svg",
  "aws_service:iot-sitewise": "Arch_AWS-IoT-SiteWise_48.svg",
  "aws_service:iot-twinmaker": "Arch_AWS-IoT-TwinMaker_48.svg",
  "aws_service:kendra": "Arch_Amazon-Kendra_48.svg",
  "aws_service:lake-formation": "Arch_AWS-Lake-Formation_48.svg",
  "aws_service:launch-wizard": "Arch_AWS-Launch-Wizard_48.svg",
  "aws_service:lex": "Arch_Amazon-Lex_48.svg",
  "aws_service:license-manager": "Arch_AWS-License-Manager_48.svg",
  "aws_service:local-zones": "Arch_AWS-Local-Zones_48.svg",
  "aws_service:location-service": "Arch_Amazon-Location-Service_48.svg",
  "aws_service:macie": "Arch_Amazon-Macie_48.svg",
  "aws_service:mainframe-modernization": "Arch_AWS-Mainframe-Modernization_48.svg",
  "aws_service:managed-blockchain": "Arch_Amazon-Managed-Blockchain_48.svg",
  "aws_service:managed-grafana": "Arch_Amazon-Managed-Grafana_48.svg",
  "aws_service:managed-service-for-prometheus": "Arch_Amazon-Managed-Service-for-Prometheus_48.svg",
  "aws_service:monitron": "Arch_Amazon-Monitron_48.svg",
  "aws_service:nova": "Arch_Amazon-Nova_48.svg",
  "aws_service:oracle-database": "Arch_Oracle-Database-at-AWS_48.svg",
  "aws_service:organizations": "Arch_AWS-Organizations_48.svg",
  "aws_service:outposts": "Arch_AWS-Outposts-family_48.svg",
  "aws_service:panorama": "Arch_AWS-Panorama_48.svg",
  "aws_service:payment-cryptography": "Arch_AWS-Payment-Cryptography_48.svg",
  "aws_service:personalize": "Arch_Amazon-Personalize_48.svg",
  "aws_service:pinpoint": "Arch_Amazon-Pinpoint_48.svg",
  "aws_service:polly": "Arch_Amazon-Polly_48.svg",
  "aws_service:proton": "Arch_AWS-Proton_48.svg",
  "aws_service:q-developer-in-chat-applications": "Arch_AWS-Chatbot_48.svg",
  "aws_service:quick": "Arch_Amazon-Quick_48.svg",
  "aws_service:rekognition": "Arch_Amazon-Rekognition_48.svg",
  "aws_service:resilience-hub": "Arch_AWS-Resilience-Hub_48.svg",
  "aws_service:resource-explorer": "Arch_AWS-Resource-Explorer_48.svg",
  "aws_service:rosa": "Arch_Red-Hat-OpenShift-Service-on-AWS_48.svg",
  "aws_service:rtb-fabric": "Arch_AWS-RTB-Fabric_48.svg",
  "aws_service:sagemaker": "Arch_Amazon-SageMaker_48.svg",
  "aws_service:sagemaker-ai": "Arch_Amazon-SageMaker-AI_48.svg",
  "aws_service:security-agent": "Arch_AWS-Security-Agent_48.svg",
  "aws_service:security-hub": "Arch_AWS-Security-Hub_48.svg",
  "aws_service:security-incident-response": "Arch_AWS-Security-Incident-Response_48.svg",
  "aws_service:security-lake": "Arch_Amazon-Security-Lake_48.svg",
  "aws_service:serverless-application-repository": "Arch_AWS-Serverless-Application-Repository_48.svg",
  "aws_service:service-catalog": "Arch_AWS-Service-Catalog_48.svg",
  "aws_service:service-management-connector": "Arch_AWS-Service-Management-Connector_48.svg",
  "aws_service:signer": "Arch_AWS-Signer_48.svg",
  "aws_service:simple-email-service": "Arch_Amazon-Simple-Email-Service_48.svg",
  "aws_service:snowball-edge": "Arch_AWS-Snowball-Edge_48.svg",
  "aws_service:storage-gateway": "Arch_AWS-Storage-Gateway_48.svg",
  "aws_service:supply-chain": "Arch_AWS-Supply-Chain_48.svg",
  "aws_service:sustainability": "Arch_AWS-Sustainability_48.svg",
  "aws_service:systems-manager": "Arch_AWS-Systems-Manager_48.svg",
  "aws_service:systems-manager-incident-manager": "Arch_AWS-Systems-Manager_48.svg",
  "aws_service:telco-network-builder": "Arch_AWS-Telco-Network-Builder_48.svg",
  "aws_service:textract": "Arch_Amazon-Textract_48.svg",
  "aws_service:transcribe": "Arch_Amazon-Transcribe_48.svg",
  "aws_service:transfer-family": "Arch_AWS-Transfer-Family_48.svg",
  "aws_service:transform": "Arch_AWS-Transform_48.svg",
  "aws_service:translate": "Arch_Amazon-Translate_48.svg",
  "aws_service:trusted-advisor": "Arch_AWS-Trusted-Advisor_48.svg",
  "aws_service:user-notifications": "Arch_AWS-User-Notifications_48.svg",
  "aws_service:wavelength": "Arch_AWS-Wavelength_48.svg",
  "aws_service:well-architected-tool": "Arch_AWS-Well-Architected-Tool_48.svg",
  "aws_service:wickr": "Arch_AWS-Wickr_48.svg",
  "aws_service:workmail": "Arch_Amazon-WorkMail_48.svg",
  "aws_service:x-ray": "Arch_AWS-X-Ray_48.svg",
  "aws_service_discovery_service": "Arch_AWS-Cloud-Map_48.svg",
  "aws_sfn_state_machine": "Arch_AWS-Step-Functions_48.svg",
  "aws_shield_protection": "Arch_AWS-Shield_48.svg",
  "aws_sns_topic": "Arch_Amazon-Simple-Notification-Service_48.svg",
  "aws_sqs_queue": "Arch_Amazon-Simple-Queue-Service_48.svg",
  "aws_ssoadmin_permission_set": "Arch_AWS-IAM-Identity-Center_48.svg",
  "aws_timestreamwrite_table": "Arch_Amazon-Timestream_48.svg",
  "aws_verifiedaccess_instance": "Arch_AWS-Verified-Access_48.svg",
  "aws_verifiedpermissions_policy_store": "Arch_Amazon-Verified-Permissions_48.svg",
  "aws_vpc": "Arch_Amazon-Virtual-Private-Cloud_48.svg",
  "aws_vpc_endpoint": "Arch_AWS-PrivateLink_48.svg",
  "aws_vpc_peering_connection": "Res_Amazon-VPC_Peering-Connection_48.svg",
  "aws_vpclattice_service": "Arch_Amazon-VPC-Lattice_48.svg",
  "aws_vpn_connection": "Arch_AWS-Site-to-Site-VPN_48.svg",
  "aws_wafv2_web_acl": "Arch_AWS-WAF_48.svg",
  "aws_workspaces_workspace": "Arch_Amazon-WorkSpaces_48.svg"
};

export const AWS_CATEGORY_ICON_FILES: Readonly<Record<string, string>> = {
  "Analytics": "Arch-Category_Analytics_48.svg",
  "Application Integration": "Arch-Category_Application-Integration_48.svg",
  "Blockchain": "Arch-Category_Blockchain_48.svg",
  "Business Applications": "Arch-Category_Business-Applications_48.svg",
  "Cloud Financial Management": "Arch-Category_Cloud-Financial-Management_48.svg",
  "Compute": "Arch-Category_Compute_48.svg",
  "Compute HPC": "Arch-Category_Compute_48.svg",
  "Containers": "Arch-Category_Containers_48.svg",
  "Cryptography & PKI": "Arch-Category_Security-Identity_48.svg",
  "Database": "Arch-Category_Databases_48.svg",
  "Developer Tools": "Arch-Category_Developer-Tools_48.svg",
  "End User Computing": "Arch-Category_End-User-Computing_48.svg",
  "Front-End Web & Mobile": "Arch-Category_Front-End-Web-Mobile_48.svg",
  "Game Development": "Arch-Category_Games_48.svg",
  "Internet of Things (IoT)": "Arch-Category_Internet-of-Things_48.svg",
  "Machine Learning": "Arch-Category_Artificial-Intelligence_48.svg",
  "Management & Governance": "Arch-Category_Management-Tools_48.svg",
  "Media Services": "Arch-Category_Media-Services_48.svg",
  "Migration & Transfer": "Arch-Category_Migration-Modernization_48.svg",
  "Networking & Content Delivery": "Arch-Category_Networking-Content-Delivery_48.svg",
  "Quantum Computing": "Arch-Category_Quantum-Technologies_48.svg",
  "Satellite": "Arch-Category_Satellite_48.svg",
  "Security, Identity, & Compliance": "Arch-Category_Security-Identity_48.svg",
  "Serverless": "Arch-Category_Serverless_48.svg",
  "Storage": "Arch-Category_Storage_48.svg"
};

export const AWS_CORE_CATEGORY_ICON_FILES: Readonly<Record<NodeType, string>> = {
  "compute": "Arch-Category_Compute_48.svg",
  "container_workload": "Arch-Category_Containers_48.svg",
  "managed_database": "Arch-Category_Databases_48.svg",
  "cache": "Arch-Category_Databases_48.svg",
  "load_balancer": "Arch-Category_Networking-Content-Delivery_48.svg",
  "queue/stream": "Arch-Category_Application-Integration_48.svg",
  "object_store": "Arch-Category_Storage_48.svg",
  "dns": "Arch-Category_Networking-Content-Delivery_48.svg",
  "network_boundary": "Arch-Category_Networking-Content-Delivery_48.svg",
  "identity": "Arch-Category_Security-Identity_48.svg",
  "external_dependency": "Arch-Category_Management-Tools_48.svg"
};

